"""modify phone column in model User

Revision ID: 60b13158ca86
Revises: 9afdd7fc31c0
Create Date: 2023-05-20 11:50:17.975576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60b13158ca86'
down_revision = '9afdd7fc31c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=13),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=13),
               existing_nullable=False)

    # ### end Alembic commands ###
