"""change id datatype in idcard from varchar(16) to bigint

Revision ID: 6d6f47fb902a
Revises: efe22870fae2
Create Date: 2023-05-23 15:09:23.283692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d6f47fb902a'
down_revision = 'efe22870fae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('id_cards', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('user_id')
        batch_op.drop_column('barbershop_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barbershop_id', mysql.VARCHAR(length=27), nullable=False))
        batch_op.add_column(sa.Column('user_id', mysql.VARCHAR(length=21), nullable=False))

    with op.batch_alter_table('id_cards', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
