"""create appointments table

Revision ID: 90f3018a5ad1
Revises: 4e49d223dd90
Create Date: 2023-05-22 15:48:57.928628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90f3018a5ad1'
down_revision = '4e49d223dd90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.String(length=21), nullable=False),
    sa.Column('schedule', sa.DateTime(), nullable=False),
    sa.Column('is_finished', sa.Boolean(), nullable=False),
    sa.Column('is_canceled', sa.Boolean(), nullable=False),
    sa.Column('will_be_canceled', sa.Boolean(), nullable=False),
    sa.Column('date_canceled', sa.DateTime(), nullable=True),
    sa.Column('barbershop_id', sa.String(length=27), nullable=False),
    sa.Column('user_id', sa.String(length=21), nullable=False),
    sa.ForeignKeyConstraint(['barbershop_id'], ['barbershops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('barbershops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_id', sa.String(length=20), nullable=False))
        batch_op.drop_constraint('reviews_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('reviews_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'appointments', ['appointment_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('user_id')
        batch_op.drop_column('barbershop_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barbershop_id', mysql.VARCHAR(length=27), nullable=False))
        batch_op.add_column(sa.Column('user_id', mysql.VARCHAR(length=21), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reviews_ibfk_1', 'barbershops', ['barbershop_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('reviews_ibfk_2', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('appointment_id')

    with op.batch_alter_table('barbershops', schema=None) as batch_op:
        batch_op.drop_column('name')

    op.drop_table('appointments')
    # ### end Alembic commands ###
