"""create barbershops table

Revision ID: aff0be5b833f
Revises: f02014026ae0
Create Date: 2023-05-22 14:58:47.919810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff0be5b833f'
down_revision = 'f02014026ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barbershops',
    sa.Column('id', sa.String(length=27), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('picture', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('user_id', sa.String(length=21), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barbershops')
    # ### end Alembic commands ###
