"""create email verif code and id card tables

Revision ID: f02014026ae0
Revises: 4914e1523371
Create Date: 2023-05-22 14:49:09.382095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02014026ae0'
down_revision = '4914e1523371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_codes',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expired_time', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=21), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code', name='email_verification_code_pk'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('id_cards',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('picture', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=21), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('picture'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('id_cards')
    op.drop_table('email_verification_codes')
    # ### end Alembic commands ###
